#!/bin/bash
for i in {300..725}
do
xrdcp root://dcache-cms-gridftp.desy.de/pnfs//desy.de/cms/tier2/store/group/upgrade/delphes_output/YR_Delphes/Delphes342pre15_hadd/TTJets_DiLept_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU/TTJets_DiLept_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_${i}_0cb.root  root://xrootd.rcac.purdue.edu//store/user/abakshi/TTBar_Delphes/TTJets_DiLept_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_${i}_0cb.root
done
